### ISSUE TITLE
Loki4j appender does not work after context refresh event

### ISSUE THREAD

**Issue by cui086** [loki4j/loki-logback-appender#230] opened 2024-04-30 20:09 UTC
Hi,

I have a spring application that uses cloud config server. After each time we refresh the config, hence firing a content refresh event. The loki append does not send out the log anymore.

I have attached a loki4j_append_time_seconds_max graph here. Please let me know how should I trouble shoot this better.

![image](https://github.com/loki4j/loki-logback-appender/assets/30624910/a1e79d8a-6493-48b6-b48d-24f17a5c8737)

**Comment by cui086** [comment] 2024-04-30 21:44
```
   | 14:39:37,158 |-INFO in com.github.loki4j.client.pipeline.AsyncBufferPipeline@3003e580 - <<< Batch #10422e19064c46 (25,999 bytes): Loki responded with status 204
   | 14:39:37,161 |-INFO in com.github.loki4j.client.pipeline.AsyncBufferPipeline@3003e580 - Drain completed
 | 14:39:37,161 |-INFO in com.github.loki4j.logback.Loki4jAppender[LOKI] - Successfully stopped
  | 14:39:22,998 |-INFO in com.github.loki4j.client.pipeline.AsyncBufferPipeline@28757abd - >>> Batch #1d9742840f8f6 (DRAIN, 132 records, 30 streams, est. size 92,449 bytes) converted to 97,223 bytes
  | 14:39:23,030 |-INFO in com.github.loki4j.client.pipeline.AsyncBufferPipeline@28757abd - <<< Batch #1d9742840f8f6 (97,223 bytes): Loki responded with status 204
   | 14:39:37,193 |-INFO in com.github.loki4j.logback.Loki4jAppender[LOKI] - Stopping...
 14:39:37,193 |-INFO in com.github.loki4j.client.pipeline.AsyncBufferPipeline@28757abd - Pipeline is draining...
  | 14:39:37,212 |-INFO in com.github.loki4j.client.pipeline.AsyncBufferPipeline@28757abd - >>> Batch #1d97777b9fd0c (DRAIN, 69 records, 17 streams, est. size 45,214 bytes) converted to 47,812 bytes
   | 14:39:37,221 |-INFO in com.github.loki4j.client.pipeline.AsyncBufferPipeline@28757abd - <<< Batch #1d97777b9fd0c (47,812 bytes): Loki responded with status 204
    | 14:39:37,243 |-INFO in com.github.loki4j.client.pipeline.AsyncBufferPipeline@28757abd - Drain completed
| 14:39:37,243 |-INFO in com.github.loki4j.logback.Loki4jAppender[LOKI] - Successfully stopped
```

Also tried with verbose enabled. But stopped after context refresh event.

**Comment by nehaev** [comment] 2024-05-04 18:46
Hi @cui086, thanks for posting this! Still I'm not sure how do I reproduce this. It would be great if anybody could provide a test or a code snippet that I can run and see the issue.

**Comment by nehaev** [comment] 2024-06-01 18:55
Closing this issue as non-reproducible. Ready to re-open it once a test or a code snippet that I can run and see the issue is available.

**Closed by nehaev** 2024-06-01 18:55 UTC
Labels: clarification needed

**Comment by tengcomplex** [comment] 2026-04-24 09:25
I had a similar problem running Spring Boot application with spring-cloud-starter-bootstrap using @RefreshScope components getting refresh events via spring-cloud-starter-bus-amqp.

Versions:
* Spring Boot 3.5.8, 4.0.5
* loki-logback-appender v1.5.2, v2.0.3

Upon startup the application initializes Loki4jAppender programmatically and appends it to the logger, logs appear in Loki.
After changing a configuration with subsequent refresh event, the application re-initializes necessary things, after that no more log entries arrive in Loki.
Deeper inspection revealed a RefreshRemoteApplicationEvent triggering `PropertySourceBootstrapConfiguration.reinitializeLoggingSystem()` which resets the logging system, effectively detaching and stopping all appenders.

What worked was to implement a `@EventListener(RefreshScopeRefreshedEvent.class) `method, adding Loki4jAppender again and additionally call stop() and start() on it. I could not see why a simple re-append is not enough and/or if this is intended.
